spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: mongodb://10.112.44.232:27017/OrionScion
    rest:
      base-path: /api
    elasticsearch:
      properties:
        index.max_result_window: 500000
        
elasticsearch:
  indexname: orionscion
  type: Article
  host: 10.112.32.252
  clustername: elasticsearch
  port: 9300
        
        
  
     
        

        
         
        